import { Component, OnInit, ViewChild } from '@angular/core';
import { FormControl, FormGroupDirective, FormBuilder, FormGroup, NgForm, Validators } from '@angular/forms';
import {AuthService } from '../Services/auth.service';
import { Observable } from 'rxjs';
import { startWith, map, sample } from 'rxjs/operators';
import { ActivatedRoute, Router } from '@angular/router';
import { _filter } from '../register/register.component';

export interface hd {
  group: string;
  mapping_id : number;
  names: string[];
}

@Component({
  selector: 'app-edit-profile',
  templateUrl: './edit-profile.component.html',
  styleUrls: ['./edit-profile.component.scss']
})
export class EditProfileComponent implements OnInit {
  // @ViewChild('religion') private religion:any;

  Details: FormGroup;
  MaritalStatus= ['Never Married', 'Awaiting Divorce', 'Divorced', 'Widowed', 'Anulled'];
  createProfile = ['saada', 'sadsdasa'];
  Heights: string[] = ['4.0"', '4.1"', '4.2"', '4.3"', '4.4"', '4.5"', '4.6"', '4.7"', '4.8"', '4.9"', '5.0', '5.1"'
  , '5.2"', '5.3"', '5.5"', '5.5"', '5.6"', '5.7"', '5.8"', '5.9"', '6.0"', '6.1"', '6.2"',
   '6.3"', '6.6"', '6.5"', '6.6"', '6.7"', '6.8"', '6.9"', '7.0"'];
  Religions: string[] = ['Hindu', 'Muslim', 'Sikh', 'Christian', 'Buddhist', 'Jain', 'Parsi', 'Jewish', 'Bahai'];
  FoodChoice=["Doesn't matter",'Non-vegetarian','Vegetarian'];
  Working : string[] = ['Working', 'Not Working', "Doesn't matter"];
  AnnualIncome: any[] = ['No Income', 'Rs 0-1 Lakh', 'Rs 1-2 Lakh', 'Rs 2-3 Lakh', 'Rs 3-4 Lakh', 'Rs 4-5 Lakh', 'Rs 5-7.5 Lakh',
  'Rs 7.5-4 Lakh',
  'Rs 4-15 Lakh', 'Rs 15-20 Lakh', 'Rs 20-25 Lakh', 'Rs 25-50 Lakh', 'Rs 50Lakh-1Crore', 'Rs 1Crore+'];
  isClicked  = true;
  identityNumber = localStorage.getItem('identityNumber');
  About: string;
  manglik_id:any;
  loggedInUserGender;
  manglikPreference = ['Manglik','Anshik Manglik'];
  nonManglikPreference = ['Non-Manglik','Anshik Manglik'];
  caste_id:any;
  prefCaste:any;
  Mangalika:[];
  Occupation:[];
  Castes:hd[];
  prefManglik:any[];
  userEditDetails : FormGroup;
  CasteOptions: Observable<hd[]>;
  caste=true;
  dropdownList:any = [];
  selectedItems = [];
  selectedItems1:any = [];
  selectedItems2:any = [];
  dropdownSettings = {};
  currentReligion:string;
  FamilyType: string[] = ['JointFamily', 'Nuclear Family', 'Others'];
  castePref:any;
  City: string[] = [
    'Achalpur',
    'Achhnera',
    'Adalaj',
    'Adilabad',
    'Adityapur',
    'Adoni',
    'Adoor',
    'Adra',
    'Adyar',
    'Afzalpur',
    'Agartala',
    'Agra',
    'Ahmedabad',
    'Ahmednagar',
    'Aizawl',
    'Ajmer',
    'Akola',
    'Akot',
    'Alappuzha',
    'Aligarh',
    'AlipurdUrban Agglomerationr',
    'Alirajpur',
    'Allahabad',
    'Alwar',
    'Amalapuram',
    'Amalner',
    'Ambejogai',
    'Ambikapur',
    'Amravati',
    'Amreli',
    'Amritsar',
    'Amroha',
    'Anakapalle',
    'Anand',
    'Anantapur',
    'Anantnag',
    'Anjangaon',
    'Anjar',
    'Ankleshwar',
    'Arakkonam',
    'Arambagh',
    'Araria',
    'Arrah',
    'Arsikere',
    'Aruppukkottai',
    'Arvi',
    'Arwal',
    'Asansol',
    'Asarganj',
    'Ashok Nagar',
    'Athni',
    'Attingal',
    'Aurangabad',
    'Aurangabad',
    'Azamgarh',
    'Bagaha',
    'Bageshwar',
    'Bahadurgarh',
    'Baharampur',
    'Bahraich',
    'Balaghat',
    'Balangir',
    'Baleshwar Town',
    'Ballari',
    'Balurghat',
    'Bankura',
    'Bapatla',
    'Baramula',
    'Barbil',
    'Bargarh',
    'Barh',
    'Baripada Town',
    'Barmer',
    'Barnala',
    'Barpeta',
    'Batala',
    'Bathinda',
    'Begusarai',
    'Belagavi',
    'Bellampalle',
    'Belonia',
    'Bengaluru',
    'Bettiah',
    'BhabUrban Agglomeration',
    'Bhadrachalam',
    'Bhadrak',
    'Bhagalpur',
    'Bhainsa',
    'Bharatpur',
    'Bharuch',
    'Bhatapara',
    'Bhavnagar',
    'Bhawanipatna',
    'Bheemunipatnam',
    'Bhilai Nagar',
    'Bhilwara',
    'Bhimavaram',
    'Bhiwandi',
    'Bhiwani',
    'Bhongir',
    'Bhopal',
    'Bhubaneswar',
    'Bhuj',
    'Bikaner',
    'Bilaspur',
    'Bobbili',
    'Bodhan',
    'Bokaro Steel City',
    'Bongaigaon City',
    'Brahmapur',
    'Buxar',
    'Byasanagar',
    'Chaibasa',
    'Chalakudy',
    'Chandausi',
    'Chandigarh',
    'Changanassery',
    'Charkhi Dadri',
    'Chatra',
    'Chennai',
    'Cherthala',
    'Chhapra',
    'Chhapra',
    'Chikkamagaluru',
    'Chilakaluripet',
    'Chirala',
    'Chirkunda',
    'Chirmiri',
    'Chittoor',
    'Chittur-Thathamangalam',
    'Coimbatore',
    'Cuttack',
    'Dalli-Rajhara',
    'Darbhanga',
    'Darjiling',
    'Davanagere',
    'Deesa',
    'Dehradun',
    'Dehri-on-Sone',
    'Delhi',
    'Deoghar',
    'Dhamtari',
    'Dhanbad',
    'Dharmanagar',
    'Dharmavaram',
    'Dhenkanal',
    'Dhoraji',
    'Dhubri',
    'Dhule',
    'Dhuri',
    'Dibrugarh',
    'Dimapur',
    'Diphu',
    'Dumka',
    'Dumraon',
    'Durg',
    'Eluru',
    'English Bazar',
    'Erode',
    'Etawah',
    'Faridabad',
    'Faridkot',
    'Farooqnagar',
    'Fatehabad',
    'Fatehpur Sikri',
    'Fazilka',
    'Firozabad',
    'Firozpur Cantt.',
    'Firozpur',
    'Forbesganj',
    'Gadwal',
    'Gandhinagar',
    'Gangarampur',
    'Ganjbasoda',
    'Gaya',
    'Giridih',
    'Goalpara',
    'Gobichettipalayam',
    'Gobindgarh',
    'Godhra',
    'Gohana',
    'Gokak',
    'Gooty',
    'Gopalganj',
    'Gudivada',
    'Gudur',
    'Gumia',
    'Guntakal',
    'Guntur',
    'Gurdaspur',
    'Gurgaon',
    'Guruvayoor',
    'Guwahati',
    'Gwalior',
    'Habra',
    'Hajipur',
    'Haldwani-cum-Kathgodam',
    'Hansi',
    'Hapur',
    'Hardoi ',
    'Hardwar',
    'Hazaribag',
    'Hindupur',
    'Hisar',
    'Hoshiarpur',
    'Hubli-Dharwad',
    'Hugli-Chinsurah',
    'Hyderabad',
    'Ichalkaranji',
    'Imphal',
    'Indore',
    'Itarsi',
    'Jabalpur',
    'Jagdalpur',
    'Jaggaiahpet',
    'Jagraon',
    'Jagtial',
    'Jaipur',
    'Jalandhar Cantt.',
    'Jalandhar',
    'Jalpaiguri',
    'Jamalpur',
    'Jammalamadugu',
    'Jammu',
    'Jamnagar',
    'Jamshedpur',
    'Jamui',
    'Jangaon',
    'Jatani',
    'Jehanabad',
    'Jhansi',
    'Jhargram',
    'Jharsuguda',
    'Jhumri Tilaiya',
    'Jind',
    'Jodhpur',
    'Jorhat',
    'Kadapa',
    'Kadi',
    'Kadiri',
    'Kagaznagar',
    'Kailasahar',
    'Kaithal',
    'Kakinada',
    'Kalimpong',
    'Kalpi',
    'Kalyan-Dombivali',
    'Kamareddy',
    'Kancheepuram',
    'Kandukur',
    'Kanhangad',
    'Kannur',
    'Kanpur',
    'Kapadvanj',
    'Kapurthala',
    'Karaikal',
    'Karimganj',
    'Karimnagar',
    'Karjat',
    'Karnal',
    'Karur',
    'Karwar',
    'Kasaragod',
    'Kashipur',
    'KathUrban Agglomeration',
    'Katihar',
    'Kavali',
    'Kayamkulam',
    'Kendrapara',
    'Kendujhar',
    'Keshod',
    'Khair',
    'Khambhat',
    'Khammam',
    'Khanna',
    'Kharagpur',
    'Kharar',
    'Khowai',
    'Kishanganj',
    'Kochi',
    'Kodungallur',
    'Kohima',
    'Kolar',
    'Kolkata',
    'Kollam',
    'Koratla',
    'Korba',
    'Kot Kapura',
    'Kota',
    'Kothagudem',
    'Kottayam',
    'Kovvur',
    'Koyilandy',
    'Kozhikode',
    'Kunnamkulam',
    'Kurnool',
    'Kyathampalle',
    'Lachhmangarh',
    'Ladnu',
    'Ladwa',
    'Lahar',
    'Laharpur',
    'Lakheri',
    'Lakhimpur',
    'Lakhisarai',
    'Lakshmeshwar',
    'Lal Gopalganj Nindaura',
    'Lalganj',
    'Lalganj',
    'Lalgudi',
    'Lalitpur',
    'Lalsot',
    'Lanka',
    'Lar',
    'Lathi',
    'Latur',
    'Lilong',
    'Limbdi',
    'Lingsugur',
    'Loha',
    'Lohardaga',
    'Lonar',
    'Lonavla',
    'Longowal',
    'Loni',
    'Losal',
    'Lucknow',
    'Ludhiana',
    'Lumding',
    'Lunawada',
    'Lunglei',
    'Macherla',
    'Machilipatnam',
    'Madanapalle',
    'Maddur',
    'Madhepura',
    'Madhubani',
    'Madhugiri',
    'Madhupur',
    'Madikeri',
    'Madurai',
    'Magadi',
    'Mahad',
    'Mahalingapura',
    'Maharajganj',
    'Maharajpur',
    'Mahasamund',
    'Mahbubnagar',
    'Mahe',
    'Mahemdabad',
    'Mahendragarh',
    'Mahesana',
    'Mahidpur',
    'Mahnar Bazar',
    'Mahuva',
    'Maihar',
    'Mainaguri',
    'Makhdumpur',
    'Makrana',
    'Malaj Khand',
    'Malappuram',
    'Malavalli',
    'Malda',
    'Malegaon',
    'Malerkotla',
    'Malkangiri',
    'Malkapur',
    'Malout',
    'Malpura',
    'Malur',
    'Manachanallur',
    'Manasa',
    'Manavadar',
    'Manawar',
    'Mancherial',
    'Mandalgarh',
    'Mandamarri',
    'Mandapeta',
    'Mandawa',
    'Mandi Dabwali',
    'Mandi',
    'Mandideep',
    'Mandla',
    'Mandsaur',
    'Mandvi',
    'Mandya',
    'Manendragarh',
    'Maner',
    'Mangaldoi',
    'Mangaluru',
    'Mangalvedhe',
    'Manglaur',
    'Mangrol',
    'Mangrol',
    'Mangrulpir',
    'Manihari',
    'Manjlegaon',
    'Mankachar',
    'Manmad',
    'Mansa',
    'Mansa',
    'Manuguru',
    'Manvi',
    'Manwath',
    'Mapusa',
    'Margao',
    'Margherita',
    'Marhaura',
    'Mariani',
    'Marigaon',
    'Markapur',
    'Marmagao',
    'Masaurhi',
    'Mathabhanga',
    'Mathura',
    'Mattannur',
    'Mauganj',
    'Mavelikkara',
    'Mavoor',
    'Mayang Imphal',
    'Medak',
    'Medininagar (Daltonganj)',
    'Medinipur',
    'Meerut',
    'Mehkar',
    'Memari',
    'Merta City',
    'Mhaswad',
    'Mhow Cantonment',
    'Mhowgaon',
    'Mihijam',
    'Mira-Bhayandar',
    'Mirganj',
    'Miryalaguda',
    'Modasa',
    'Modinagar',
    'Moga',
    'Mohali',
    'Mokameh',
    'Mokokchung',
    'Monoharpur',
    'Moradabad',
    'Morena',
    'Morinda, India',
    'Morshi',
    'Morvi',
    'Motihari',
    'Motipur',
    'Mount Abu',
    'Mudabidri',
    'Mudalagi',
    'Muddebihal',
    'Mudhol',
    'Mukerian',
    'Mukhed',
    'Muktsar',
    'Mul',
    'Mulbagal',
    'Multai',
    'Mumbai',
    'Mundargi',
    'Mundi',
    'Mungeli',
    'Munger',
    'Murliganj',
    'Murshidabad',
    'Murtijapur',
    'Murwara (Katni)',
    'Musabani',
    'Mussoorie',
    'Muvattupuzha',
    'Muzaffarpur',
    'Mysore',
    'Nabadwip',
    'Nabarangapur',
    'Nabha',
    'Nadbai',
    'Nadiad',
    'Nagaon',
    'Nagapattinam',
    'Nagar',
    'Nagari',
    'Nagarkurnool',
    'Nagaur',
    'Nagda',
    'Nagercoil',
    'Nagina',
    'Nagla',
    'Nagpur',
    'Nahan',
    'Naharlagun',
    'Naidupet',
    'Naihati',
    'Naila Janjgir',
    'Nainital',
    'Nainpur',
    'Najibabad',
    'Nakodar',
    'Nakur',
    'Nalbari',
    'Namagiripettai',
    'Namakkal',
    'Nanded-Waghala',
    'Nandgaon',
    'Nandivaram-Guduvancheri',
    'Nandura',
    'Nandurbar',
    'Nandyal',
    'Nangal',
    'Nanjangud',
    'Nanjikottai',
    'Nanpara',
    'Narasapuram',
    'Narasaraopet',
    'Naraura',
    'Narayanpet',
    'Nargund',
    'Narkatiaganj',
    'Narkhed',
    'Narnaul',
    'Narsinghgarh',
    'Narsinghgarh',
    'Narsipatnam',
    'Narwana',
    'Nashik',
    'Nasirabad',
    'Natham',
    'Nathdwara',
    'Naugachhia',
    'Naugawan Sadat',
    'Nautanwa',
    'Navalgund',
    'Navsari',
    'Nawabganj',
    'Nawada',
    'Nawanshahr',
    'Nawapur',
    'Nedumangad',
    'Neem-Ka-Thana',
    'Neemuch',
    'Nehtaur',
    'Nelamangala',
    'Nellikuppam',
    'Nellore',
    'Nepanagar',
    'New Delhi',
    'Neyveli (TS)',
    'Neyyattinkara',
    'Nidadavole',
    'Nilambur',
    'Nilanga',
    'Nimbahera',
    'Nirmal',
    'Niwai',
    'Niwari',
    'Nizamabad',
    'Nohar',
    'Noida',
    'Nokha',
    'Nokha',
    'Nongstoin',
    'Noorpur',
    'North Lakhimpur',
    'Nowgong',
    'Nowrozabad (Khodargama)',
    'Nuzvid',
    'O\' Valley',
    'Obra',
    'Oddanchatram',
    'Ongole',
    'Orai',
    'Osmanabad',
    'Ottappalam',
    'Ozar',
    'P.N.Patti',
    'Pachora',
    'Pachore',
    'Pacode',
    'Padmanabhapuram',
    'Padra',
    'Padrauna',
    'Paithan',
    'Pakaur',
    'Palacole',
    'Palai',
    'Palakkad',
    'Palampur',
    'Palani',
    'Palanpur',
    'Palasa Kasibugga',
    'Palghar',
    'Pali',
    'Pali',
    'Palia Kalan',
    'Palitana',
    'Palladam',
    'Pallapatti',
    'Pallikonda',
    'Palwal',
    'Palwancha',
    'Panagar',
    'Panagudi',
    'Panaji',
    'Panamattom',
    'Panchkula',
    'Panchla',
    'Pandharkaoda',
    'Pandharpur',
    'Pandhurna',
    'PandUrban Agglomeration',
    'Panipat',
    'Panna',
    'Panniyannur',
    'Panruti',
    'Panvel',
    'Pappinisseri',
    'Paradip',
    'Paramakudi',
    'Parangipettai',
    'Parasi',
    'Paravoor',
    'Parbhani',
    'Pardi',
    'Parlakhemundi',
    'Parli',
    'Partur',
    'Parvathipuram',
    'Pasan',
    'Paschim Punropara',
    'Pasighat',
    'Patan',
    'Pathanamthitta',
    'Pathankot',
    'Pathardi',
    'Pathri',
    'Patiala',
    'Patna',
    'Patratu',
    'Pattamundai',
    'Patti',
    'Pattran',
    'Pattukkottai',
    'Patur',
    'Pauni',
    'Pauri',
    'Pavagada',
    'Pedana',
    'Peddapuram',
    'Pehowa',
    'Pen',
    'Perambalur',
    'Peravurani',
    'Peringathur',
    'Perinthalmanna',
    'Periyakulam',
    'Periyasemur',
    'Pernampattu',
    'Perumbavoor',
    'Petlad',
    'Phagwara',
    'Phalodi',
    'Phaltan',
    'Phillaur',
    'Phulabani',
    'Phulera',
    'Phulpur',
    'Phusro',
    'Pihani',
    'Pilani',
    'Pilibanga',
    'Pilibhit',
    'Pilkhuwa',
    'Pindwara',
    'Pinjore',
    'Pipar City',
    'Pipariya',
    'Piriyapatna',
    'Piro',
    'Pithampur',
    'Pithapuram',
    'Pithoragarh',
    'Pollachi',
    'Polur',
    'Pondicherry',
    'Ponnani',
    'Ponneri',
    'Ponnur',
    'Porbandar',
    'Porsa',
    'Port Blair',
    'Powayan',
    'Prantij',
    'Pratapgarh',
    'Pratapgarh',
    'Prithvipur',
    'Proddatur',
    'Pudukkottai',
    'Pudupattinam',
    'Pukhrayan',
    'Pulgaon',
    'Puliyankudi',
    'Punalur',
    'Punch',
    'Pune',
    'Punganur',
    'Punjaipugalur',
    'Puranpur',
    'Puri',
    'Purna',
    'Purnia',
    'PurqUrban Agglomerationzi',
    'Purulia',
    'Purwa',
    'Pusad',
    'Puthuppally',
    'Puttur',
    'Puttur',
    'Qadian',
    'Raayachuru',
    'Rabkavi Banhatti',
    'Radhanpur',
    'Rae Bareli',
    'Rafiganj',
    'Raghogarh-Vijaypur',
    'Raghunathganj',
    'Raghunathpur',
    'Rahatgarh',
    'Rahuri',
    'Raiganj',
    'Raigarh',
    'Raikot',
    'Raipur',
    'Rairangpur',
    'Raisen',
    'Raisinghnagar',
    'Rajagangapur',
    'Rajahmundry',
    'Rajakhera',
    'Rajaldesar',
    'Rajam',
    'Rajampet',
    'Rajapalayam',
    'Rajauri',
    'Rajgarh (Alwar)',
    'Rajgarh (Churu)',
    'Rajgarh',
    'Rajgir',
    'Rajkot',
    'Rajnandgaon',
    'Rajpipla',
    'Rajpura',
    'Rajsamand',
    'Rajula',
    'Rajura',
    'Ramachandrapuram',
    'Ramagundam',
    'Ramanagaram',
    'Ramanathapuram',
    'Ramdurg',
    'Rameshwaram',
    'Ramganj Mandi',
    'Ramgarh',
    'Ramnagar',
    'Ramnagar',
    'Ramngarh',
    'Rampur Maniharan',
    'Rampur',
    'Rampura Phul',
    'Rampurhat',
    'Ramtek',
    'Ranaghat',
    'Ranavav',
    'Ranchi',
    'Ranebennuru',
    'Rangia',
    'Rania',
    'Ranibennur',
    'Ranipet',
    'Rapar',
    'Rasipuram',
    'Rasra',
    'Ratangarh',
    'Rath',
    'Ratia',
    'Ratlam',
    'Ratnagiri',
    'Rau',
    'Raurkela',
    'Raver',
    'Rawatbhata',
    'Rawatsar',
    'Raxaul Bazar',
    'Rayachoti',
    'Rayadurg',
    'Rayagada',
    'Reengus',
    'Rehli',
    'Renigunta',
    'Renukoot',
    'Reoti',
    'Repalle',
    'Revelganj',
    'Rewa',
    'Rewari',
    'Rishikesh',
    'Risod',
    'Robertsganj',
    'Robertson Pet',
    'Rohtak',
    'Ron',
    'Roorkee',
    'Rosera',
    'Rudauli',
    'Rudrapur',
    'Rudrapur',
    'Rupnagar',
    'Sabalgarh',
    'Sadabad',
    'Sadalagi',
    'Sadasivpet',
    'Sadri',
    'Sadulpur',
    'Sadulshahar',
    'Safidon',
    'Safipur',
    'Sagar',
    'Sagara',
    'Sagwara',
    'Saharanpur',
    'Saharsa',
    'Sahaspur',
    'Sahaswan',
    'Sahawar',
    'Sahibganj',
    'Sahjanwa',
    'Saidpur',
    'Saiha',
    'Sailu',
    'Sainthia',
    'Sakaleshapura',
    'Sakti',
    'Salaya',
    'Salem',
    'Salur',
    'Samalkha',
    'Samalkot',
    'Samana',
    'Samastipur',
    'Sambalpur',
    'Sambhal',
    'Sambhar',
    'Samdhan',
    'Samthar',
    'Sanand',
    'Sanawad',
    'Sanchore',
    'Sandi',
    'Sandila',
    'Sanduru',
    'Sangamner',
    'Sangareddy',
    'Sangaria',
    'Sangli',
    'Sangole',
    'Sangrur',
    'Sankarankovil',
    'Sankari',
    'Sankeshwara',
    'Santipur',
    'Sarangpur',
    'Sardarshahar',
    'Sardhana',
    'Sarni',
    'Sarsod',
    'Sasaram',
    'Sasvad',
    'Satana',
    'Satara',
    'Sathyamangalam',
    'Satna',
    'Sattenapalle',
    'Sattur',
    'Saunda',
    'Saundatti-Yellamma',
    'Sausar',
    'Savanur',
    'Savarkundla',
    'Savner',
    'Sawai Madhopur',
    'Sawantwadi',
    'Sedam',
    'Sehore',
    'Sendhwa',
    'Seohara',
    'Seoni',
    'Seoni-Malwa',
    'Shahabad',
    'Shahabad, Hardoi',
    'Shahabad, Rampur',
    'Shahade',
    'Shahbad',
    'Shahdol',
    'Shahganj',
    'Shahjahanpur',
    'Shahpur',
    'Shahpura',
    'Shahpura',
    'Shajapur',
    'Shamgarh',
    'Shamli',
    'Shamsabad, Agra',
    'Shamsabad, Farrukhabad',
    'Shegaon',
    'Sheikhpura',
    'Shendurjana',
    'Shenkottai',
    'Sheoganj',
    'Sheohar',
    'Sheopur',
    'Sherghati',
    'Sherkot',
    'Shiggaon',
    'Shikaripur',
    'Shikarpur, Bulandshahr',
    'Shikohabad',
    'Shillong',
    'Shimla',
    'Shirdi',
    'Shirpur-Warwade',
    'Shirur',
    'Shishgarh',
    'Shivamogga',
    'Shivpuri',
    'Sholavandan',
    'Sholingur',
    'Shoranur',
    'Shrigonda',
    'Shrirampur',
    'Shrirangapattana',
    'Shujalpur',
    'Siana',
    'Sibsagar',
    'Siddipet',
    'Sidhi',
    'Sidhpur',
    'Sidlaghatta',
    'Sihor',
    'Sihora',
    'Sikanderpur',
    'Sikandra Rao',
    'Sikandrabad',
    'Sikar',
    'Silao',
    'Silapathar',
    'Silchar',
    'Siliguri',
    'Sillod',
    'Silvassa',
    'Simdega',
    'Sindagi',
    'Sindhagi',
    'Sindhnur',
    'Singrauli',
    'Sinnar',
    'Sira',
    'Sircilla',
    'Sirhind Fatehgarh Sahib',
    'Sirkali',
    'Sirohi',
    'Sironj',
    'Sirsa',
    'Sirsaganj',
    'Sirsi',
    'Sirsi',
    'Siruguppa',
    'Sitamarhi',
    'Sitapur',
    'Sitarganj',
    'Sivaganga',
    'Sivagiri',
    'Sivakasi',
    'Siwan',
    'Sohagpur',
    'Sohna',
    'Sojat',
    'Solan',
    'Solapur',
    'Sonamukhi',
    'Sonepur',
    'Songadh',
    'Sonipat',
    'Sopore',
    'Soro',
    'Soron',
    'Soyagaon',
    'Sri Madhopur',
    'Srikakulam',
    'Srikalahasti',
    'Srinagar',
    'Srinagar',
    'Srinivaspur',
    'Srirampore',
    'Srisailam Project (Right Flank Colony) Township',
    'Srivilliputhur',
    'Sugauli',
    'Sujangarh',
    'Sujanpur',
    'Sullurpeta',
    'Sultanganj',
    'Sultanpur',
    'Sumerpur',
    'Sumerpur',
    'Sunabeda',
    'Sunam',
    'Sundargarh',
    'Sundarnagar',
    'Supaul',
    'Surandai',
    'Surapura',
    'Surat',
    'Suratgarh',
    'SUrban Agglomerationr',
    'Suri',
    'Suriyampalayam',
    'Suryapet',
    'Tadepalligudem',
    'Tadpatri',
    'Takhatgarh',
    'Taki',
    'Talaja',
    'Talcher',
    'Talegaon Dabhade',
    'Talikota',
    'Taliparamba',
    'Talode',
    'Talwara',
    'Tamluk',
    'Tanda',
    'Tandur',
    'Tanuku',
    'Tarakeswar',
    'Tarana',
    'Taranagar',
    'Taraori',
    'Tarbha',
    'Tarikere',
    'Tarn Taran',
    'Tasgaon',
    'Tehri',
    'Tekkalakote',
    'Tenali',
    'Tenkasi',
    'Tenu dam-cum-Kathhara',
    'Terdal',
    'Tezpur',
    'Thakurdwara',
    'Thammampatti',
    'Thana Bhawan',
    'Thane',
    'Thanesar',
    'Thangadh',
    'Thanjavur',
    'Tharad',
    'Tharamangalam',
    'Tharangambadi',
    'Theni Allinagaram',
    'Thirumangalam',
    'Thirupuvanam',
    'Thiruthuraipoondi',
    'Thiruvalla',
    'Thiruvallur',
    'Thiruvananthapuram',
    'Thiruvarur',
    'Thodupuzha',
    'Thoubal',
    'Thrissur',
    'Thuraiyur',
    'Tikamgarh',
    'Tilda Newra',
    'Tilhar',
    'Tindivanam',
    'Tinsukia',
    'Tiptur',
    'Tirora',
    'Tiruchendur',
    'Tiruchengode',
    'Tiruchirappalli',
    'Tirukalukundram',
    'Tirukkoyilur',
    'Tirunelveli',
    'Tirupathur',
    'Tirupathur',
    'Tirupati',
    'Tiruppur',
    'Tirur',
    'Tiruttani',
    'Tiruvannamalai',
    'Tiruvethipuram',
    'Tiruvuru',
    'Tirwaganj',
    'Titlagarh',
    'Tittakudi',
    'Todabhim',
    'Todaraisingh',
    'Tohana',
    'Tonk',
    'Tuensang',
    'Tuljapur',
    'Tulsipur',
    'Tumkur',
    'Tumsar',
    'Tundla',
    'Tuni',
    'Tura',
    'Uchgaon',
    'Udaipur',
    'Udaipur',
    'Udaipurwati',
    'Udgir',
    'Udhagamandalam',
    'Udhampur',
    'Udumalaipettai',
    'Udupi',
    'Ujhani',
    'Ujjain',
    'Umarga',
    'Umaria',
    'Umarkhed',
    'Umbergaon',
    'Umred',
    'Umreth',
    'Una',
    'Unjha',
    'Unnamalaikadai',
    'Unnao',
    'Upleta',
    'Uran Islampur',
    'Uran',
    'Uravakonda',
    'Urmar Tanda',
    'Usilampatti',
    'Uthamapalayam',
    'Uthiramerur',
    'Utraula',
    'Vadakkuvalliyur',
    'Vadalur',
    'Vadgaon Kasba',
    'Vadipatti',
    'Vadnagar',
    'Vadodara',
    'Vaijapur',
    'Vaikom',
    'Valparai',
    'Valsad',
    'Vandavasi',
    'Vaniyambadi',
    'Vapi',
    'Vapi',
    'Varanasi',
    'Varkala',
    'Vasai-Virar',
    'Vatakara',
    'Vedaranyam',
    'Vellakoil',
    'Vellore',
    'Venkatagiri',
    'Veraval',
    'Vidisha',
    'Vijainagar, Ajmer',
    'Vijapur',
    'Vijayapura',
    'Vijayawada',
    'Vijaypur',
    'Vikarabad',
    'Vikramasingapuram',
    'Viluppuram',
    'Vinukonda',
    'Viramgam',
    'Virudhachalam',
    'Virudhunagar',
    'Visakhapatnam',
    'Visnagar',
    'Viswanatham',
    'Vita',
    'Vizianagaram',
    'Vrindavan',
    'Vyara',
    'Wadgaon Road',
    'Wadhwan',
    'Wadi',
    'Wai',
    'Wanaparthy',
    'Wani',
    'Wankaner',
    'Wara Seoni',
    'Warangal',
    'Wardha',
    'Warhapur',
    'Warisaliganj',
    'Warora',
    'Warud',
    'Washim',
    'Wokha',
    'Yadgir',
    'Yamunanagar',
    'Yanam',
    'Yavatmal',
    'Yawal',
    'Yellandu',
    'Yemmiganur',
    'Yerraguntla',
    'Yevla',
    'Zaidpur',
    'Zamania',
    'Zira',
    'Zirakpur',
    'Zunheboto',
  ];
  citis: Observable<string[]>;
  constructor(private auth: AuthService, private _formBuilder: FormBuilder, private route:ActivatedRoute,private router:Router ) {

    this.userEditDetails = this._formBuilder.group({
            identity_number:[''],   
            about : [''],
            name:[''],
            birth_date:[''],
            marital_status:[''],
            religion:[''],
            height:[''],
            weight:[''],
            food_choice:[''],
            caste : [''],
            subcaste : [''],
            city : [''],
            degree : [''],
            college : [''],
            occupation : [''],
            annual_income : [''],
            manglik : [''],
            address : [''],
            mobile : [''],
            family_type : [''],
            family_about : [''],
            occupation_father : [''],
            occupation_mother : [''],
            married_sons : [''],
            married_daughters : [''],
            unmarried_daughters: [''],
            unmarried_sons : [''],
            locality : [''],
            family_city:[''],
            family_address:[''],
            pref_caste:[[]],
            pref_marital_status:[''],
            pref_manglik:[''],
            working:[''],
            pref_food_choice:[''],

            

       })

    
  }
  private _Castefilter(value: string): hd[] {
    if (value) {
      return this.Castes
        .map(group => ({ group: group.group, names: _filter(group.names, value),mapping_id: group.mapping_id }))
        .filter(group => group.names.length > 0);
    }
    return this.Castes;
  }

  private _filter(value: string): string[] {
    const filterValue = value.toLowerCase();

    return this.Religions.filter(option => option.toLowerCase().indexOf(filterValue) === 0);
  }

  private _profilefilter(value: string): string[] {
    const filterValue = value.toLowerCase();

    return this.createProfile.filter(option => option.toLowerCase().indexOf(filterValue) === 0);
  }
  scroll(anchor: string) {
    const element = document.querySelector('#' + anchor);
    element.scrollIntoView({ behavior: 'smooth', });
    this.isClicked = false;
  }

  ngOnInit() {
  
   

    const iden = new FormData();
    iden.append('identity_number', this.identityNumber);

    
    this.auth.getProfile(iden).subscribe((res: any) => {
      console.log(res);
      this.loggedInUserGender = res.profile.gender;
      console.log(this.loggedInUserGender);
      this.manglik_id = res.profile.manglik_id;
      this.caste_id = res.profile.caste_id;
         console.log(this.manglik_id,this.caste_id);
      if(this.manglik_id == 'Manglik')
    { 
      console.log('svs1'); 
      this.prefManglik = this.manglikPreference;
    }
    else if(this.manglik_id == 'Non-manglik')  
    {
      console.log('svs2'); 
      this.prefManglik = this.nonManglikPreference;
    }
    else
    { 
      this.prefManglik = []; 
      this.prefManglik.push("Doesn't matter");
    }
      console.log('ade',this.prefManglik,this.caste_id);
      for(let items of res.preferences.caste)
    {
      let prefCastes = res.preferences.caste;
      prefCastes = prefCastes.split(',');
      this.selectedItems2 = prefCastes;
      
    }
    console.log(this.selectedItems2);
      this.userEditDetails.patchValue({
        identity_number : this.identityNumber,
        about : res.profile.about,
        name:res.profile.name,
        birth_date:res.profile.birth_date,
        marital_status:res.profile.marital_status,
        religion:res.family.religion,
        height:res.profile.height,
        weight:res.profile.weight,
        food_choice:res.profile.food_choice,
        caste : res.family.caste,
        subcaste : res.family.sub_caste,
        city : res.family.city,
        degree : res.profile.degree,
        college : res.profile.college,
        occupation : res.profile.occupation,
        annual_income : res.profile.monthly_income,
        manglik : res.profile.manglik,
        address : res.family.address,
        mobile : res.family.mobile,
        family_type : res.family.family_type,
        family_about : res.family.about,
        occupation_father : res.family.occupation,
        occupation_mother : res.family.occupation_mother,
        married_sons : res.family.married_sons,
        married_daughters : res.family.married_daughters,
        unmarried_daughters: res.family.unmarried_daughters,
        unmarried_sons : res.family.unmarried_sons,
        locality : res.family.locality,
        family_city : res.family.city,
        family_address : res.family.address,
        pref_caste : this.selectedItems2,
        pref_marital_status : res.preferences.marital_status,
        pref_manglik : res.preferences.manglik,
        working : res.preferences.working,
        pref_food_choice : res.preferences.food_choice
      });
      this.About = res.profile.about;
      this.prefCaste = res.preferences.caste;
      this.prefCaste = this.prefCaste.split(',');
      this.currentReligion = res.family.religion;
      console.log('sri',this.currentReligion);
      let selectReligion = document.getElementById('selectReligion');
    selectReligion.click();
      this.getCastesAgain();

    });
    // tslint:disable-next-line:no-non-null-assertion
    console.log('sada',this.userEditDetails);
    console.log(this.MaritalStatus);

    this.dropdownSettings = { 
      singleSelection: false, 
      text:"Select Castes",
      selectAllText:'Select All',
      unSelectAllText:'UnSelect All',
      enableSearchFilter: true,
      classes:"myclass custom-class"
    };  
    
  }
  
  getCastesAgain()
  {

    console.log("get casted called");
    this.auth.getCastes().subscribe((res)=>{
      this.castePref = res;
      console.log(res);
    if(this.castePref)
   { this.castePref = this.castePref.filter( elem=>{ return elem.mapping_id==this.caste_id});
      console.log(this.castePref);
      if(this.castePref[0].castes.length>0)
      this.castePref = this.castePref[0].castes.split(',');
      console.log('castePref',this.castePref);
      for(let i=0;i<this.prefCaste.length;i++ )
      {
      this.selectedItems1.push({
          id : i+1,
          itemName : this.prefCaste[i]
        })
      }
     console.log('sfsa',this.castePref);
      if(this.caste_id && this.castePref)
      {
      for(let i=0;i<this.castePref.length;i++ )
      {
      this.dropdownList.push({
          id : i+1,
          itemName : this.castePref[i]
        })
      }
    }
      this.selectedItems = this.selectedItems1;
      console.log('a',this.dropdownList);
      console.log('b',this.selectedItems);
  
    }
    })

    }

  postEditDetails()
  {
     return this.auth.updateUser(this.userEditDetails.value).subscribe(res=>{
       console.log(res);
       this.router.navigate(['/dashboard']);
     })
  }
  
  

  Religion(event) {
    let inputReligion = event.currentTarget.value;
    console.log('sart',inputReligion);
    if(inputReligion != 'Hindu' && inputReligion != 'Muslim' && inputReligion != 'Sikh' && inputReligion != 'Jain' ) 
    {
      inputReligion = this.currentReligion;
    }
    console.log('ak',inputReligion);

    if (inputReligion === 'Hindu') {
      this.Castes = [{
        group: 'A',
        mapping_id:4,
        names: [
          'Ad Dharmi',
          'Adi Andhra',
          'Adi Dravida',
          'Adi Karnataka',
          'Agamudayar',
          'Aggarwal',
          'Agri',
          'Ahir',
          'Ahom',
          'Ambalavasi',
          'Arora',
          'Arunthathiyar',
          'Arya Vysya']
      }, {
        group: 'B',
        mapping_id:2,
        names: ['Baghel/Gaderiya',
          'Baidya',
          'Baishnab',
          'Baishya',
          'Balija',
          'Balija Naidu',
          'Bania',
          'Banik',
          'Banjara',
          'Bari',
          'Barujibi',
          'Besta',
          'Bhandari',
          'Bhatia',
          'Bhatraju',
          'Bhavsar',
          'Bhovi/Bhoi',
          'Billava',
          'Bisa Agarwal',
          'Bishnoi/Vishnoi',
          'Boyer',
          'Brahmbatt',
          'Brahmin',
          'Brahmin 6000 Niyogi',
          'Brahmin Anavil',
          'Brahmin Audichya',
          'Brahmin Bajkhedwal',
          'Brahmin Bardai',
          'Brahmin Barendra',
          'Brahmin Bhargava',
          'Brahmin Bhatt',
          'Brahmin Bhumihar',
          'Brahmin Brahacharanam',
          'Brahmin BrahmBhatt',
          'Brahmin Brajastha Mathil',
          'Brahmin Dadhich',
          'Brahmin Daivadnya',
          'Brahmin Deshastha',
          'Brahmin Deshastha',
          'Brahmin Dhiman',
          'Brahmin Dravida',
          'Brahmin Dunua',
          'Brahmin Embrandiri',
          'Brahmin Garhwali',
          'Brahmin Gaud Saraswat (GSB)',
          'Brahmin Gaur',
          'Brahmin Goswami',
          'Brahmin Gujar Gaur',
          'Brahmin Gurukkal',
          'Brahmin Halua',
          'Brahmin Havyaka',
          'Brahmin Hoysala',
          'Brahmin Iyengar',
          'Brahmin Iyer',
          'Brahmin Jangid',
          'Brahmin Jangra',
          'Brahmin Jhadua',
          'Brahmin Jhijhotiya',
          'Brahmin Jogi',
          'Brahmin Jyotish',
          'Brahmin Kanyakubj',
          'Brahmin Karhade',
          'Brahmin Kashmiri Pandit',
          'Brahmin Khadayat',
          'Brahmin Khandelwal',
          'Brahmin Khedaval',
          'Brahmin Koknastha',
          'Brahmin Kota',
          'Brahmin Kulin',
          'Brahmin Kumaoni',
          'Brahmin Madhwa',
          'Brahmin Maithil',
          'Brahmin Malviya',
          'Brahmin Mevada',
          'Brahmin Modh',
          'Brahmin Mohyal',
          'Brahmin Nagar',
          'Brahmin Namboodiri',
          'Brahmin Narmadiya',
          'Brahmin Paliwal',
          'Brahmin Panda',
          'Brahmin Pandit',
          'Brahmin Panicker',
          'Brahmin Pareek',
          'Brahmin Pushkarna',
          'Brahmin Rajgor',
          'Brahmin Rarhi',
          'Brahmin Rigvedi',
          'Brahmin Rudraj',
          'Brahmin Sakaldwipi',
          'Brahmin Sanadya',
          'Brahmin Sanketi',
          'Brahmin Saraswat',
          'Brahmin Sarua',
          'Brahmin Saryuparin',
          'Brahmin Shivalli',
          'Brahmin Shrimali',
          'Brahmin Sikhwal',
          'Brahmin Smartha',
          'Brahmin Sri Vishnava',
          'Brahmin Stanika',
          'Brahmin Tapodhan',
          'Brahmin Tyagi',
          'Brahmin Vaidiki',
          'Brahmin Vaikhawas',
          'Brahmin Valam',
          'Brahmin Velanadu',
          'Brahmin Viswa',
          'Brahmin Vyas',
          'Brahmin Yajurvedi',
          'Brahmin Zalora',
          'Brahmo',
          'Bunt/Shetty']
      },
      {
        group: 'C',
        mapping_id:4,
        names: [
          'Chamar', 'Chambhar', 'Chandravanshi Kahar', 'Chasa', 'Chattada Sri Vaishnava', 'Chaudary'
          , 'Chaurasia', 'Chettiar', 'Chhetri', 'CKP', 'Coorgi']
      },
      {
        group: 'D',
        mapping_id:4,
        names: ['Deshastha Maratha',
          'Devadigas',
          'Devang Koshthi',
          'Devanga',
          'Devendra Kula Vellalar',
          'Dhangar',
          'Dheevara',
          'Dhoba',
          'Dhobi',
          'Dusadh']
      },
      {
        group: 'E',
        mapping_id:4,
        names: ['Edigas', 'Ezhava', 'Ezhuthachan']
      },
      {
        group: 'G',
        mapping_id:3,
        names: ['Gabit',
          'Ganiga',
          'Garhwali',
          'Gavali',
          'Gavara',
          'Ghumar',
          'Goala',
          'Goan',
          'Gomantak Maratha',
          'Gondhali',
          'Goud',
          'Gounder',
          'Gowda',
          'Gramani',
          'Gudia',
          'Gujjar',
          'Gupta',
          'Gurav']
      },
      {
        group: 'H',
        mapping_id:4,
        names: ['Hegde']
      },
      {
        group: 'J',
        mapping_id:4,
        names: ['Jaiswal', 'Jangam', 'Jat', 'Jatav']
      },
      {
        group: 'K',
        mapping_id:1,
        names: ['Kadava patel',
          'Kahar',
          'Kaibarta',
          'Kalal',
          'Kalar',
          'Kalinga Vysya',
          'Kalwar',
          'Kamboj',
          'Kamma',
          'Kansari',
          'Kapol',
          'Kapu',
          'Kapu Munnuru',
          'Karana',
          'Karmakar',
          'Karuneegar',
          'Kasar',
          'Kashyap',
          'Kayastha',
          'Khandayat',
          'Khandelwal',
          'Kharwar',
          'Khatik',
          'Khatri',
          'Kokanastha Maratha',
          'Koli',
          'Koli Mahadev',
          'Kongu Vellala Gounder',
          'Konkani',
          'Kori',
          'Koshti',
          'Kshatriya',
          'Kshatriya Agnikula',
          'Kudumbi',
          'Kulalar',
          'Kulita',
          'Kumawat',
          'Kumbhakar',
          'Kumhar/Kumbhar',
          'Kummari',
          'Kunbi',
          'Kurmi',
          'Kurmi kshatriya',
          'Kuruba',
          'Kuruhina shetty',
          'Kurumbar',
          'Kushwaha',
          'Kutchi',
          'Kutchi Gurjar']
      },
      {
        group: 'L',
        mapping_id:4,
        names: [
          'Lambadi',
          'Leva Patidar',
          'Leva Patil',
          'Lingayat',
          'Lodhi Rajput',
          'Lohana',
          'Lohar',
          'Lubana'
        ]
      },

        // {
        //   group: 'Doctorate',
        
        //   names: ["Ph.D", "M.Phil"]
        // ,
        // {
        //   group: 'Doctorate',
        
        //   names: ["Ph.D", "M.Phil"]
        // ,

        // {
        //   group: 'Doctorate',
        
        //   names: ["Ph.D", "M.Phil"]
        // ,
        // {
        //   group: 'Doctorate',
        
        //   names: ["Ph.D", "M.Phil"]
        // ,
        // {
        //   group: 'Doctorate',
        
        //   names: ["Ph.D", "M.Phil"]
        // ,
        // {
        //   group: 'Doctorate',
        
        //   names: ["Ph.D", "M.Phil"]
        // },
        // {
        //   group: 'Doctorate',
        
        //   names: ["Ph.D", "M.Phil"]
        // },
        // {
        //   group: 'Doctorate',
        
        //   names: ["Ph.D", "M.Phil"]
        // },
        // {
        //   group: 'Doctorate',
        
        //   names: ["Ph.D", "M.Phil"]
        // },
        // {
        //   group: 'Doctorate',
        
        //   names: ["Ph.D", "M.Phil"]
        // },
        // {
        //   group: 'Doctorate',
        
        //   names: ["Ph.D", "M.Phil"]
        // },
        // {
        //   group: 'Doctorate',
        
        //   names: ["Ph.D", "M.Phil"]
        // }
      ];
    } else if (inputReligion === 'Muslim') {
      this.Castes = [
        {
          group: 'S',
          mapping_id:4,
          names: ['Shia', 'Sunni']
        }
      ];
    } else if (inputReligion === 'Sikh') {
      this.Castes = [
        {
          group: 'A',
          mapping_id:4,
          names: ['Arora']
        },
        {
          group: 'B',
          mapping_id:4,
          names: ['Bhatia']
        },
        {
          group: 'G',
          mapping_id:4,
          names: ['Gurkish']
        },
        {
          group: 'j',
          mapping_id:4,
          names: ['jat']
        },
        {
          group: 'l',
          mapping_id:4,
          names: ['Labana']
        },
        {
          group: 'M',
          mapping_id:4,
          names: ['Mazbhi']
        },
        {
          group: 'O',
          mapping_id:4,
          names: ['Others']
        },
        {
          group: 'R',
          mapping_id:4,
          names: ['Rajput', 'Rmadasia', 'Ramagharia']
        },
        {
          group: 'S',
          mapping_id:4,
          names: ['Saini']
        },
      ];
    } else if (inputReligion === 'Jain') {
      this.Castes = [
        {
          group: 'D',
          mapping_id:4,
          names: ['Digamber']
        },
        {
          group: 'O',
          mapping_id:4,
          names: ['Others']
        },
        {
          group: 'S',
          mapping_id:4,
          names: ['Shwetamber']
        },
      ];
    
    }
  }

  onItemSelect(item:any){
    console.log(item);
    console.log(this.selectedItems);
}
OnItemDeSelect(item:any){
    console.log(item);
    console.log(this.selectedItems);
}
onSelectAll(items: any){
    console.log(items);
}
onDeSelectAll(items: any){
    console.log(items);
}
}